### ISSUE TITLE
I found that I could not enter the discussion group.

### ISSUE THREAD

**Issue by HunterHeidy** [wangcunxiang/SemEval2020-Task4-Commonsense-Validation-and-Explanation#5]
I did this type of task for the first time. I wanted to find a similar task reference. When I entered the discussion group, I found that I didn't have permission to access it.

**Comment by wangcunxiang** [comment]
Sorry, I'm not sure what 'discussion group' do you refer to? Could you be more specific?

**Comment by anandhperumal** [comment]
@wangcunxiang competition forum which is given in the Coda Lab for the Sem eval task 4.

**Comment by HunterHeidy** [comment]
> 
> 
> Sorry, I'm not sure what 'discussion group' do you refer to? Could you be more specific?

task organisers and competition forum in Codaloab，I don't have permission to enter

**Comment by HunterHeidy** [comment]
> 
> 
> @wangcunxiang competition forum which is given in the Coda Lab for the Sem eval task 4.

but I don't have permission to enter,

**Comment by Shuailong** [comment]
@HunterHeidy @anandhperumal 

Hi, you need to *participate* into the competition first in order to post in the Forum on Codalab. It is under "Pariticipate" Tab of the competition page. After we approve your participation request, you should be able to post.

You are encouraged to email to the organizers first at **semeval-2020-task-4-organizers@googlegroups.com** should you have any questions regarding to the task or dataset. This email address previously has some permission issue, sorry, now we have fixed it already.

**Comment by anandhperumal** [comment]
@Shuailong  I'm already a participant but I'm not using Gmail I think that's the issue. Can someone look into it?

**Comment by Shuailong** [comment]
You can email to semeval-2020-task-4-organizers@googlegroups.com using any email address to contact organizers. For now, since the members are not stabilized, we do not use semeval-2020-task-4-all@googlegroups.com to post announcement. Instead we use Codalab to send messages to all participants.

**Comment by anandhperumal** [comment]
@Shuailong okay but just to bring it to your notice I didn't receive any message so far.

**Comment by Shuailong** [comment]
@anandhperumal No worries. We will notify you if there is something important that you need to know.

**Comment by anandhperumal** [comment]
@Shuailong Thanks
